# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'other_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from tkinter import Label

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
from PyQt5.QtWidgets import QVBoxLayout, QLabel, QAction, QStyleFactory, QApplication, QSplitter, QFrame, QHBoxLayout, \
    QWidget
from views.AutoResizeLabel import AutoResizeLabel


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):

        self.main_centralwidget = QtWidgets.QWidget(OtherWindow)
        self.main_centralwidget.setObjectName("main_centralwidget")

        hbox = QHBoxLayout(self.main_centralwidget)
        # Left Pannel
        self.left = QFrame(OtherWindow)
        self.left.setFrameShape(QFrame.StyledPanel)

        self.class_verticalLayout = QtWidgets.QVBoxLayout()
        self.class_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.class_verticalLayout.setObjectName("verticalLayout")

        self.class_verticalLayout.setStretch(2, 5)

        spacerItem = QtWidgets.QSpacerItem(100, 500, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.class_verticalLayout.addItem(spacerItem)
        self.left.setLayout(self.class_verticalLayout)

        # Right Pannel
        self.right = QFrame(OtherWindow)
        self.right.setFrameShape(QFrame.StyledPanel)

        self.img_verticalLayout = QtWidgets.QVBoxLayout()
        self.img_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)

        '''self.image_label = QLabel(self.right)
        self.pixmap = QtGui.QPixmap('new_img.png')
        # self.pixmap_resized = self.pixmap.scaled(850, 550, QtCore.Qt.KeepAspectRatio)
        self.image_label.setPixmap(self.pixmap)
        self.image_label.setObjectName('Image')
        # self.main_layout = QVBoxLayout()  # adding widgets to layot

        self.img_verticalLayout.addWidget(self.image_label)'''


        #lay = QVBoxLayout(self)
        self.lb = AutoResizeLabel(self.right)
        self.lb.setPixmap(QPixmap(''))
        #lay.addWidget(lb)
        self.img_verticalLayout.addWidget(self.lb)


        self.right.setLayout(self.img_verticalLayout)

        splitter = QSplitter(QtCore.Qt.Horizontal)
        splitter.addWidget(self.left)
        splitter.addWidget(self.right)
        splitter.setStretchFactor(1, 1)
        splitter.setSizes([125, 150])
        hbox.addWidget(splitter)
        OtherWindow.setLayout(hbox)

        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(900, 600)

        OtherWindow.setCentralWidget(self.main_centralwidget)

        self.menubar = QtWidgets.QMenuBar(OtherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu.setTitle("Исходные данные")

        self.open_input_file = QAction(icon=QIcon('web.jpg'), text='Исходный файл', parent=OtherWindow)
        self.open_input_file.setShortcut('Ctrl+O')
        self.open_input_file.setStatusTip('Вырать исходный файл для анализа')

        self.menu.addAction(self.open_input_file)

        self.add_class_dir = QAction(QIcon('open.png'), 'Добавить класс', OtherWindow)
        self.add_class_dir.setShortcut('Ctrl+P')
        self.add_class_dir.setStatusTip('Добавить класс для обучения')

        self.menu.addAction(self.add_class_dir)

        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_2.setTitle("Настройки обработки")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_3.setTitle("Обсчёт")

        self.run_main_task = QAction(QIcon('open.png'), 'Запустить обсчёт', OtherWindow)
        self.run_main_task.setShortcut('Ctrl+R')
        self.run_main_task.setStatusTip('Запустить классификацию и обсчёт исходного изображения')

        self.menu_3.addAction(self.run_main_task)

        OtherWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(OtherWindow)
        self.statusbar.setObjectName("statusbar")
        OtherWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        QtCore.QMetaObject.connectSlotsByName(OtherWindow)



