# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'other_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
from PyQt5.QtWidgets import QVBoxLayout, QLabel, QAction, QStyleFactory, QApplication, QSplitter, QFrame, QHBoxLayout


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        hbox = QHBoxLayout(OtherWindow)
        left = QFrame(self)
        left.setFrameShape(QFrame.StyledPanel)
        right = QFrame(self)
        right.setFrameShape(QFrame.StyledPanel)
        splitter = QSplitter(QtCore.Qt.Horizontal)
        splitter.addWidget(left)
        splitter.addWidget(right)
        splitter.setStretchFactor(1, 1)
        splitter.setSizes([125, 150])
        hbox.addWidget(splitter)
        self.setLayout(hbox)
        #QApplication.setStyle(QStyleFactory.create('Cleanlooks'))
        #self.setGeometry(300, 300, 300, 200)
        #self.setWindowTitle('QtGui.QSplitter')

        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(900, 600)

        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 831, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        # horizontalLayout
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        # self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # verticalLayout
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.verticalLayout.setContentsMargins(0, 0, 0, 0)


        self.verticalLayout.setStretch(2, 5)

        spacerItem = QtWidgets.QSpacerItem(100, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        # verticalLayout_2 -> horizontalLayout
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.image_label = QLabel()
        self.pixmap = QtGui.QPixmap('')
        # self.pixmap_resized = self.pixmap.scaled(850, 550, QtCore.Qt.KeepAspectRatio)
        self.image_label.setPixmap(self.pixmap)
        self.image_label.setObjectName('Image')
        # self.main_layout = QVBoxLayout()  # adding widgets to layot

        self.verticalLayout_2.addWidget(self.image_label)

        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(2, 5)

        # OtherWindow.setCentralWidget(self.centralwidget)
        OtherWindow.setCentralWidget(hbox)





        self.menubar = QtWidgets.QMenuBar(OtherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu.setTitle("Исходные данные")

        self.open_input_file = QAction(icon=QIcon('web.jpg'), text='Исходный файл', parent=OtherWindow)
        self.open_input_file.setShortcut('Ctrl+O')
        self.open_input_file.setStatusTip('Вырать исходный файл для анализа')

        self.menu.addAction(self.open_input_file)

        self.add_class_dir = QAction(QIcon('open.png'), 'Добавить класс', OtherWindow)
        self.add_class_dir.setShortcut('Ctrl+P')
        self.add_class_dir.setStatusTip('Добавить класс для обучения')

        self.menu.addAction(self.add_class_dir)

        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_2.setTitle("Настройки обработки")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_3.setTitle("Обсчёт")

        self.run_main_task = QAction(QIcon('open.png'), 'Запустить обсчёт', OtherWindow)
        self.run_main_task.setShortcut('Ctrl+R')
        self.run_main_task.setStatusTip('Запустить классификацию и обсчёт исходного изображения')

        self.menu_3.addAction(self.run_main_task)

        OtherWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(OtherWindow)
        self.statusbar.setObjectName("statusbar")
        OtherWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        QtCore.QMetaObject.connectSlotsByName(OtherWindow)



